sudo: false

dist: xenial

language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly


matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - test "$TRAVIS_PHP_VERSION" != "nightly" || export COMPOSER_FLAGS="$COMPOSER_FLAGS --ignore-platform-reqs"

install:
  - composer install --prefer-source $COMPOSER_FLAGS

script:
  # Search for PHP syntax errors.
  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  ## PHPUnit
  - composer test
  # Validate the composer.json file.
  # @link https://getcomposer.org/doc/03-cli.md#validate
  - composer validate --strict --no-check-lock
  ## PHP_CodeSniffer
  - ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1
  ## PHP Mess Detector
  - if [[ "$EXTRA_CHECKS" == "1" ]]; then ./vendor/bin/phpmd ./classes/src/ text ./phpmd.xml.dist; fi
  ## PHPLOC
  - if [[ "$EXTRA_CHECKS" == "1" ]]; then ./vendor/bin/phploc ./classes/src/; fi
  ## PHPStan
  # - composer phpstan
  ## Infection
  - composer infection

notifications:
  email: false
